### PR TITLE
Include tests for different scenarios with -x

### PR DESCRIPTION
**Pull request by xsawyerx**
This provides tests for both #86 and #87. Their resolution is https://github.com/cpanel/Overload-FileCheck/pull/21 but the tests will serve as regression tests.

### CODE REVIEW

**Comment by atoomic** [comment]
this is cool, we would also have to bump the version requirement for Overload-FileCheck once released

**Comment by xsawyerx** [comment]
Force pushed another change. This was not merged somehow.

**Comment by xsawyerx** [comment]
I manually merged it and pushed to the repo.

**Comment by atoomic** [comment]
We definitively need some similar tests ( in a light version ) to Overload-FileCheck

**Pull request merged**
