### PR TITLE
Tidy everything

### PR DESCRIPTION
**Pull request by xsawyerx**
This is ready to be merged after #79.

### CODE REVIEW

**Review by atoomic — APPROVED** [review]

**Comment by atoomic** [comment]
Which policy are we using? is it part of the repo?
if not we should consider adding it, as this has some public exposition

**Comment by xsawyerx** [comment]
Using this one: https://github.com/cpanel/Test-MockFile/blob/master/.perltidyrc.

(Do not merge this until #79 is merged since it includes those commits.)

**Comment by toddr** [comment]
> Using this one: https://github.com/cpanel/Test-MockFile/blob/master/.perltidyrc.
> 
> (Do not merge this until #79 is merged since it includes those commits.)

The version of perltidy matters a lot. ideally it would be cpanel-perl-532's tidy.

**Comment by xsawyerx** [comment]
I was using the one you introduced. I'll copy the right one over.

**Pull request closed without merging**
